version: '3.8'

services:
  fastapi-app:
    environment:
      - OLLAMA_API_HOST=http://ollama:11434
    networks:
      - mynetwork
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8030:8000"
    volumes:
      - ./app:/app
    depends_on:
      - ollama

  ollama:
    image: ollama/ollama:latest
    deploy:
      resources:
        limits:
          memory: 6G
        reservations:
          memory: 4G
    networks:
      - mynetwork
    ports:
      - "11434:11434"
    volumes:
      - ollama_data:/root/.ollama
    entrypoint: ["/bin/sh", "-c", "
      ollama serve &
      while ! ollama list > /dev/null 2>&1; do
      echo 'Ожидание запуска Ollama...';
      sleep 2;
      done;
      echo 'Ollama запущен!';
      ollama pull mistral;
      while ! ollama list | grep -q 'mistral'; do
          echo 'Ожидание загрузки mistral...';
          sleep 10;
      done;
      echo 'Модель mistral загружена.';
      wait %1
      "]

    

volumes:
  ollama_data:

networks:
  mynetwork:
    name: mynetwork